inherit kde-base

need-kde 3.1

SRC_URI="mirror://sourceforge/calcchecksum/${PN}-1.6-pre1.tar.bz2"
HOMEPAGE="http://calcchecksum.sf.net"
DESCRIPTION=" CalcChecksum is a tool for calculating MD5, MD4, CRC32, SHA1 (SHA160), SHA256, RIPE-MD-160, TIGER, HAVAL (128, 160, 192, 224, 256 with 3, 4 or 5 passes) on files, text-strings or hash-lists generated by md5sum or sha1sum."

KEYWORDS="~x86"

S=${WORKDIR}/${PN}-1.6-pre1

src_compile() {
    econf --prefix=$KDEDIR
    emake
}
