diff -ru wmjiface/src/Makefile wmjiface.new/src/Makefile
--- wmjiface/src/Makefile	Tue Nov 14 14:28:27 2000
+++ wmjiface.new/src/Makefile	Sat Aug 31 19:13:24 2002
@@ -1,13 +1,13 @@
-prefix=/home/jettero/bin
-#owner=-o root
-#group=-g root
+#prefix=/home/jettero/bin
+owner=-o root
+group=-g root
 
 # Makefile for ${name}
 # <mfischer@umr.edu>
 # based on wmWeather - see ../Credits for more information
 
 CC     = gcc
-CFLAGS = #-O2 -g #-Wall # I think this option is idiotic
+CFLAGS = -O2 #-g #-Wall # I think this option is idiotic
 INCDIR = -I/usr/X11R6/include/X11 -I/usr/X11R6/include #-I/usr/i386-glibc20-linux/include
 DESTDIR= /usr/X11R6
 LIBDIR = -L/usr/X11R6/lib
diff -ru wmjiface/src/xutils/Makefile wmjiface.new/src/xutils/Makefile
--- wmjiface/src/xutils/Makefile	Sat Oct 30 23:33:39 1999
+++ wmjiface.new/src/xutils/Makefile	Sat Aug 31 19:15:23 2002
@@ -3,7 +3,7 @@
 # based on wmWeather - see ../Credits for more information
 
 CC     = gcc
-CFLAGS = #-O2 -g #-Wall # I think this option is idiotic
+CFLAGS = -O2 #-g #-Wall # I think this option is idiotic
 INCDIR = -I/usr/X11R6/include/X11 -I/usr/X11R6/include
 DESTDIR= /usr/X11R6
 LIBDIR = -L/usr/X11R6/lib
